---
deployment:
  tasks:
    - export DEPLOYPATH=/home/ciasceco/public_html/
    - /usr/bin/rsync -a --exclude='.git' --exclude='.cpanel.yml' --exclude='.env' --exclude='vendor/' --exclude='storage/' ./ $DEPLOYPATH
